#!/bin/sh

set -e -u

cp -a mergedeep ${AUTOPKGTEST_TMP}

for py3vers in $(py3versions -s); do
    echo
    echo "***************************"
    echo "*** Testing with ${py3vers}"
    echo "***************************"
    echo
    cd ${AUTOPKGTEST_TMP} && \
        echo "Content of current working folder:\n" && \
        ls -la && \
        echo "\nRunning tests...\n" && \
        ${py3vers} -m unittest discover -v
done

echo

exit 0
